name: Run Stock Bot

on:
  workflow_dispatch: # 讓你隨時可以在網頁上按按鈕立即執行
  schedule:
    - cron: '30 0 * * 1-5' # 台北時間週一到週五早上 8:30 自動執行 (UTC 時間)

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests yfinance

      - name: Run script
        run: |
          python test1.py
